# Dependencies
markdown:         kramdown
highlighter:      pygments

# Plugins
plugins:
  - jekyll-gist

# include:
#   - _plugins
#   - _projects
#   - public
#   - images

# Permalinks
permalink:        pretty

# Setup
title:            "Nilesh Balu"
tagline:          ""
description:      ""
url:              "http://nileshbalu.github.io"
baseurl:          "/"

author:
  name:           'Nilesh Balu'
  url:            

paginate:         5

collections:
  projects:
    output:       true
    permalink:    /projects/:path/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
