# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Nilesh Balu"
tagline:          'Personal Webpage'
description:      'Overview of my academic journey'
url:              "http://NileshBalu.github.io"
baseurl:          /

author:
  name:           'Nilesh Balu'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
